In [294]:
import pandas as pd
import inflection
import re
import numpy as np

In [160]:
df0 = pd.read_json('as24_cars.json')
df = df0.copy()
df.head()

,make_model,short_description,make,model,location,price,Body type,Type,Doors,Country version,...,CO₂-efficiency,Fuel consumption (WLTP),CO₂-emissions (WLTP),Available from,Taxi or rental car,Availability,Last timing belt change,Electric Range (WLTP),Power consumption (WLTP),Battery Ownership
0,Mercedes-Benz A 160,CDi,\nMercedes-Benz\n,"[\n, A 160 ,\n]","P.I. EL PALMAR C/FORJA 6, 11500 PUERTO DE SAN...","€ 16,950.-","[\n, Compact, \n]","[\n, Used, \n]","[\n, 5, \n]","[\n, Spain, \n]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mercedes-Benz EQE 350,350+,\nMercedes-Benz\n,"[\n, EQE 350 ,\n]","APARTADO DE CORREOS 1032, 26140 LOGROÑO, ES","€ 80,900.-","[\n, Compact, \n]","[\n, Pre-registered, \n]","[\n, 4, \n]","[\n, Spain, \n]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,\nMercedes-Benz\n,"[\n, A 45 AMG ,\n]","PORT. TARRACO, MOLL DE LLEVANT, Nº 5, LOC. 6-8...","€ 69,900.-","[\n, Compact, \n]","[\n, Used, \n]","[\n, 5, \n]","[\n, Spain, \n]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mercedes-Benz A 35 AMG,4Matic+ 7G-DCT,\nMercedes-Benz\n,"[\n, A 35 AMG ,\n]","Carrer de Provença, 31 Local, 8029 BARCELONA, ES","€ 46,990.-","[\n, Compact, \n]","[\n, Used, \n]","[\n, 5, \n]","[\n, Spain, \n]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mercedes-Benz A 45 AMG,200CDI BE Line 4M 7G-DCT,\nMercedes-Benz\n,"[\n, A 45 AMG ,\n]","CARRIL ARAGONES 4, 30007 CASILLAS, ES","€ 16,800.-","[\n, Compact, \n]","[\n, Used, \n]","[\n, 5, \n]","[\n, Spain, \n]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29480 entries, 0 to 29479
Data columns (total 58 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   make_model                28630 non-null  object
 1   short_description         28630 non-null  object
 2   make                      28630 non-null  object
 3   model                     28630 non-null  object
 4   location                  28630 non-null  object
 5   price                     28630 non-null  object
 6   Body type                 28630 non-null  object
 7   Type                      28630 non-null  object
 8   Doors                     28271 non-null  object
 9   Country version           16889 non-null  object
 10  Offer number              23100 non-null  object
 11  Warranty                  15784 non-null  object
 12  Mileage                   28629 non-null  object
 13  First registration        28628 non-null  object
 14  Gearbox                   28382 non-null  object
 15  Fuel type                 26843 non-null  object
 16  Colour                    26906 non-null  object
 17  Paint                     14495 non-null  object
 18  desc                      28047 non-null  object
 19  seller                    28630 non-null  object
 20  Seats                     25505 non-null  object
 21  Power                     28058 non-null  object
 22  Engine size               27227 non-null  object
 23  Gears                     18954 non-null  object
 24  CO₂-emissions             18594 non-null  object
 25  Manufacturer colour       21787 non-null  object
 26  Drivetrain                16893 non-null  object
 27  Cylinders                 18852 non-null  object
 28  Fuel consumption          23385 non-null  object
 29
Comfort & Convenience
   25433 non-null  object
 30
Entertainment & Media
   23644 non-null  object
 31
Safety & Security
       25415 non-null  object
 32
Extras
                  23480 non-null  object
 33  Empty weight              17758 non-null  object
 34  Model code                8367 non-null   object
 35  General inspection        12254 non-null  object
 36  Last service              2003 non-null   object
 37  Full service history      12565 non-null  object
 38  Non-smoker vehicle        11594 non-null  object
 39  Emission class            17859 non-null  object
 40  Emissions sticker         9414 non-null   object
 41  Upholstery colour         14569 non-null  object
 42  Upholstery                18610 non-null  object
 43  Production date           5908 non-null   float64
 44  Previous owner            14015 non-null  object
 45  Other fuel types          2313 non-null   object
 46  Power consumption         515 non-null    object
 47  Energy efficiency class   7804 non-null   object
 48  CO₂-efficiency            7804 non-null   object
 49  Fuel consumption (WLTP)   100 non-null    object
 50  CO₂-emissions (WLTP)      116 non-null    object
 51  Available from            393 non-null    object
 52  Taxi or rental car        422 non-null    object
 53  Availability              301 non-null    object
 54  Last timing belt change   572 non-null    object
 55  Electric Range (WLTP)     16 non-null     object
 56  Power consumption (WLTP)  16 non-null     object
 57  Battery Ownership         7 non-null      object
dtypes: float64(1), object(57)
memory usage: 13.0+ MB

In [162]:
df.describe(include='all')

,make_model,short_description,make,model,location,price,Body type,Type,Doors,Country version,...,CO₂-efficiency,Fuel consumption (WLTP),CO₂-emissions (WLTP),Available from,Taxi or rental car,Availability,Last timing belt change,Electric Range (WLTP),Power consumption (WLTP),Battery Ownership
count,28630,28630,28630,28630,28630,28630,28630,28630,28271,16889,...,7804,100,116,393,422,301,572,16,16,7
unique,611,20947,13,594,8181,5021,6,4,6,25,...,1,47,68,125,1,18,86,14,13,1
top,Renault Megane,,\nVolvo\n,"[\n, Megane ,\n]","Av. Laboral, 10, 28021 MADRID, ES","€ 14,990.-","[\n, Station wagon, \n]","[\n, Used, \n]","[\n, 5, \n]","[\n, Germany, \n]",...,Calculated on basis of measured CO₂-emissions ...,5.5 l/100 km,0 g/km (comb.),"[\n, 01/03/2023, \n]",Yes,"[\n, in 1 day after order, \n]",04/2022,426 km492 km (within city),21.9 kWh/100 km,Included
freq,863,213,3659,863,306,222,5448,25251,17481,7939,...,7804,9,14,34,422,64,27,2,2,7
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [163]:
def convert_to_snake_case(df):
    df.columns = [
        inflection.underscore(
            col.strip().replace("&", "").replace("(", "").replace(")", "").replace("-", "").replace(" ", "_").replace("__", "_")
        )
        for col in df.columns
    ]
    return df

In [164]:
df = convert_to_snake_case(df)

In [165]:
df.columns

Index(['make_model', 'short_description', 'make', 'model', 'location', 'price',
       'body_type', 'type', 'doors', 'country_version', 'offer_number',
       'warranty', 'mileage', 'first_registration', 'gearbox', 'fuel_type',
       'colour', 'paint', 'desc', 'seller', 'seats', 'power', 'engine_size',
       'gears', 'co₂emissions', 'manufacturer_colour', 'drivetrain',
       'cylinders', 'fuel_consumption', 'comfort_convenience',
       'entertainment_media', 'safety_security', 'extras', 'empty_weight',
       'model_code', 'general_inspection', 'last_service',
       'full_service_history', 'nonsmoker_vehicle', 'emission_class',
       'emissions_sticker', 'upholstery_colour', 'upholstery',
       'production_date', 'previous_owner', 'other_fuel_types',
       'power_consumption', 'energy_efficiency_class', 'co₂efficiency',
       'fuel_consumption_wltp', 'co₂emissions_wltp', 'available_from',
       'taxi_or_rental_car', 'availability', 'last_timing_belt_change',
       'electric_range_wltp', 'power_consumption_wltp', 'battery_ownership'],
      dtype='object')

In [166]:
def calculate_null_percentage(df):
   
    total_count = len(df)
    df_info = pd.DataFrame({
        "Column": df.columns,
        "Non-Null Count": df.notnull().sum(),
        "Total Count": total_count,
    })
    
    df_info['Null Count'] = df_info['Total Count'] - df_info['Non-Null Count']
    df_info['Null Percentage'] = (df_info['Null Count'] / df_info['Total Count']) * 100
    df_info_sorted = df_info[['Column', 'Null Percentage']].sort_values(by='Null Percentage', ascending=False)
    return df_info_sorted

In [167]:
sorted_nulls = calculate_null_percentage(df)

In [168]:
sorted_nulls.head(13)

                                          Column  Null Percentage
battery_ownership              battery_ownership        99.976255
power_consumption_wltp    power_consumption_wltp        99.945726
electric_range_wltp          electric_range_wltp        99.945726
fuel_consumption_wltp      fuel_consumption_wltp        99.660787
co₂emissions_wltp              co₂emissions_wltp        99.606513
availability                        availability        98.978969
available_from                    available_from        98.666893
taxi_or_rental_car            taxi_or_rental_car        98.568521
power_consumption              power_consumption        98.253053
last_timing_belt_change  last_timing_belt_change        98.059701
last_service                        last_service        93.205563
other_fuel_types                other_fuel_types        92.154003
production_date                  production_date        79.959294

In [169]:
columns_to_drop = ['battery_ownership', 'power_consumption_wltp', 'electric_range_wltp', 'fuel_consumption_wltp',
                  'co₂emissions_wltp', 'co₂emissions_wltp', 'availability', 'available_from', 'taxi_or_rental_car',
                  'power_consumption', 'last_timing_belt_change', 'last_service', 'other_fuel_types']

In [170]:
df.drop(columns=columns_to_drop, axis=1, inplace=True)

In [171]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29480 entries, 0 to 29479
Data columns (total 46 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28630 non-null  object
 1   short_description        28630 non-null  object
 2   make                     28630 non-null  object
 3   model                    28630 non-null  object
 4   location                 28630 non-null  object
 5   price                    28630 non-null  object
 6   body_type                28630 non-null  object
 7   type                     28630 non-null  object
 8   doors                    28271 non-null  object
 9   country_version          16889 non-null  object
 10  offer_number             23100 non-null  object
 11  warranty                 15784 non-null  object
 12  mileage                  28629 non-null  object
 13  first_registration       28628 non-null  object
 14  gearbox                  28382 non-null  object
 15  fuel_type                26843 non-null  object
 16  colour                   26906 non-null  object
 17  paint                    14495 non-null  object
 18  desc                     28047 non-null  object
 19  seller                   28630 non-null  object
 20  seats                    25505 non-null  object
 21  power                    28058 non-null  object
 22  engine_size              27227 non-null  object
 23  gears                    18954 non-null  object
 24  co₂emissions             18594 non-null  object
 25  manufacturer_colour      21787 non-null  object
 26  drivetrain               16893 non-null  object
 27  cylinders                18852 non-null  object
 28  fuel_consumption         23385 non-null  object
 29  comfort_convenience      25433 non-null  object
 30  entertainment_media      23644 non-null  object
 31  safety_security          25415 non-null  object
 32  extras                   23480 non-null  object
 33  empty_weight             17758 non-null  object
 34  model_code               8367 non-null   object
 35  general_inspection       12254 non-null  object
 36  full_service_history     12565 non-null  object
 37  nonsmoker_vehicle        11594 non-null  object
 38  emission_class           17859 non-null  object
 39  emissions_sticker        9414 non-null   object
 40  upholstery_colour        14569 non-null  object
 41  upholstery               18610 non-null  object
 42  production_date          5908 non-null   float64
 43  previous_owner           14015 non-null  object
 44  energy_efficiency_class  7804 non-null   object
 45  co₂efficiency            7804 non-null   object
dtypes: float64(1), object(45)
memory usage: 10.3+ MB

In [172]:
df = df.map(lambda item: item[0] if type(item) == list else item)

In [173]:
df = df.map(lambda x: x.replace("\n", "").replace("\n,", "").replace(",\n", "").replace(",", "").strip() if isinstance(x, str) else x)

In [174]:
df['price'] = df['price'].str.replace("[^0-9]", "", regex=True).astype(float)

In [175]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29480 entries, 0 to 29479
Data columns (total 46 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28630 non-null  object
 1   short_description        28630 non-null  object
 2   make                     28630 non-null  object
 3   model                    28630 non-null  object
 4   location                 28630 non-null  object
 5   price                    28630 non-null  float64
 6   body_type                28630 non-null  object
 7   type                     28630 non-null  object
 8   doors                    28271 non-null  object
 9   country_version          16889 non-null  object
 10  offer_number             23100 non-null  object
 11  warranty                 15784 non-null  object
 12  mileage                  28629 non-null  object
 13  first_registration       28628 non-null  object
 14  gearbox                  28382 non-null  object
 15  fuel_type                26843 non-null  object
 16  colour                   26906 non-null  object
 17  paint                    14495 non-null  object
 18  desc                     28047 non-null  object
 19  seller                   28630 non-null  object
 20  seats                    25505 non-null  object
 21  power                    28058 non-null  object
 22  engine_size              27227 non-null  object
 23  gears                    18954 non-null  object
 24  co₂emissions             18594 non-null  object
 25  manufacturer_colour      21787 non-null  object
 26  drivetrain               16893 non-null  object
 27  cylinders                18852 non-null  object
 28  fuel_consumption         23385 non-null  object
 29  comfort_convenience      25433 non-null  object
 30  entertainment_media      23644 non-null  object
 31  safety_security          25415 non-null  object
 32  extras                   23480 non-null  object
 33  empty_weight             17758 non-null  object
 34  model_code               8367 non-null   object
 35  general_inspection       12254 non-null  object
 36  full_service_history     12565 non-null  object
 37  nonsmoker_vehicle        11594 non-null  object
 38  emission_class           17859 non-null  object
 39  emissions_sticker        9414 non-null   object
 40  upholstery_colour        14569 non-null  object
 41  upholstery               18610 non-null  object
 42  production_date          5908 non-null   float64
 43  previous_owner           14015 non-null  object
 44  energy_efficiency_class  7804 non-null   object
 45  co₂efficiency            7804 non-null   object
dtypes: float64(2), object(44)
memory usage: 10.3+ MB

In [176]:
df.head()

,make_model,short_description,make,model,location,price,body_type,type,doors,country_version,...,full_service_history,nonsmoker_vehicle,emission_class,emissions_sticker,upholstery_colour,upholstery,production_date,previous_owner,energy_efficiency_class,co₂efficiency
0,Mercedes-Benz A 160,CDi,Mercedes-Benz,A 160,P.I. EL PALMAR C/FORJA 6 11500 PUERTO DE SANT...,16950.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Mercedes-Benz EQE 350,350+,Mercedes-Benz,EQE 350,APARTADO DE CORREOS 1032 26140 LOGROÑO ES,80900.0,Compact,Pre-registered,4,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A 45 AMG,PORT. TARRACO MOLL DE LLEVANT Nº 5 LOC. 6-8 4...,69900.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Mercedes-Benz A 35 AMG,4Matic+ 7G-DCT,Mercedes-Benz,A 35 AMG,Carrer de Provença 31 Local 8029 BARCELONA ES,46990.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Mercedes-Benz A 45 AMG,200CDI BE Line 4M 7G-DCT,Mercedes-Benz,A 45 AMG,CARRIL ARAGONES 4 30007 CASILLAS ES,16800.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [177]:
df.fuel_type.value_counts()

fuel_type
Gasoline                                                                                              8532
Diesel                                                                                                5911
Super 95                                                                                              3557
Diesel (Particle filter)                                                                              2816
Regular/Benzine 91                                                                                    2065
Super E10 95                                                                                          1016
Regular/Benzine 91 (Particle filter)                                                                   555
Super 95 (Particle filter)                                                                             537
Super E10 95 (Particle filter)                                                                         324
Regular/Benzine E10 91                                                                                 278
Others                                                                                                 197
Gasoline (Particle filter)                                                                             196
Electric                                                                                               185
Super Plus 98                                                                                          170
Liquid petroleum gas (LPG)                                                                             148
CNG                                                                                                     87
LPG                                                                                                     73
Super Plus E10 98                                                                                       42
Super Plus E10 98 (Particle filter)                                                                     35
Domestic gas H                                                                                          24
Others (Particle filter)                                                                                16
Super Plus 98 (Particle filter)                                                                         15
Domestic gas L                                                                                          10
Regular/Benzine E10 91 (Particle filter)                                                                 8
CNG (Particle filter)                                                                                    8
LPG (Particle filter)                                                                                    4
Hydrogen                                                                                                 3
Liquid petroleum gas (LPG) (Particle filter) / Super 95 / Super E10 95                                   3
Electric (Particle filter)                                                                               3
Ethanol                                                                                                  3
Liquid petroleum gas (LPG) / Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95                 2
Liquid petroleum gas (LPG) / Super 95 / Super E10 95 / Super Plus 98                                     2
Liquid petroleum gas (LPG) / Super 95                                                                    2
Liquid petroleum gas (LPG) (Particle filter)                                                             2
Domestic gas L (Particle filter)                                                                         2
Liquid petroleum gas (LPG) / Super 95 / Super E10 95                                                     2
Domestic gas H / Super E10 95 / Super Plus E10 98 / Super 95 / Super Plus 98 / Domestic gas L            1
Domestic gas L / Super 95 / Domestic gas H                                                               1
Super 95 / Super Plus 98 / Liquid petroleum gas (LPG)                                                    1
Biogas                                                                                                   1
Liquid petroleum gas (LPG) / Super 95 / Super Plus 98                                                    1
Liquid petroleum gas (LPG) / Super E10 95                                                                1
Liquid petroleum gas (LPG) / Super E10 95 / Super Plus E10 98 / Super Plus 98 / Super 95                 1
Liquid petroleum gas (LPG) / Super E10 95 / Regular/Benzine 91 / Super 95 / Super Plus 98 / Biogas       1
Super 95 (Particle filter) / Super E10 95 / Ethanol                                                      1
Super 95 / Liquid petroleum gas (LPG)                                                                    1
Name: count, dtype: int64

In [178]:

benzine = ["Gasoline", "Super 95", 'Regular/Benzine 91', "Super E10 95", "Regular/Benzine 91 (Particle filter)", 
           "Super 95 (Particle filter)", "Super E10 95 (Particle filter)", "Regular/Benzine E10 91 ", "Super Plus 98",
           "Super Plus E10 98", "Super Plus E10 98 (Particle filter)", 'Others', "Others (Particle filter)", 
           "Super Plus 98 (Particle filter)", "Regular/Benzine E10 91 (Particle filter)", "Regular/Benzine E10 91", 
           "Gasoline (Particle filter)", "Super 95 (Particle filter) / Super E10 95 / Ethanol", "Ethanol"]
lpg = ["Liquid petroleum gas (LPG)", "Domestic gas L", "CNG (Particle filter)", "LPG (Particle filter) ","Liquid petroleum gas",
       "Liquid petroleum gas (LPG) (Particle filter)","LPG", "CNG", "Biogas", "Domestic gas H", "LPG (Particle filter)",
       "Domestic gas L (Particle filter)", "Hydrogen"]

lpg_benzine = ['Liquid petroleum gas (LPG) (Particle filter) / Super 95 / Super E10 95','Liquid petroleum gas (LPG) / Super 95 / Super E10 95',
              'Liquid petroleum gas (LPG) / Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95', 'Liquid petroleum gas (LPG) / Super 95',
              'Liquid petroleum gas (LPG) / Super 95 / Super E10 95 / Super Plus 98', 'Liquid petroleum gas (LPG) / Super E10 95', 
              'Liquid petroleum gas (LPG) / Super E10 95 / Super Plus E10 98 / Super Plus 98 / Super 95', 
               'Domestic gas H / Super E10 95 / Super Plus E10 98 / Super 95 / Super Plus 98 / Domestic gas L',
               'Liquid petroleum gas (LPG) / Super 95 / Super Plus 98', 'Super 95 / Super Plus 98 / Liquid petroleum gas (LPG)',
               'Domestic gas L / Super 95 / Domestic gas H', 
               'Liquid petroleum gas (LPG) / Super E10 95 / Regular/Benzine 91 / Super 95 / Super Plus 98 / Biogas',
               'Super 95 / Liquid petroleum gas (LPG)']

diesel = ['Diesel', 'Diesel (Particle filter)']

electric = ['Electric', 'Electric (Particle filter)']

def fueltype(x):
    if x in benzine:
        return "Benzine"
    elif x in lpg:
        return 'LPG/CNG'
    elif x in lpg_benzine:
        return 'LPG/Benzine'
    elif x in diesel:
        return 'Diesel'
    elif x in electric:
        return 'Electric'
    else:
        return x

In [179]:
df['fuel'] = df.fuel_type.apply(fueltype)

In [180]:
df.fuel.value_counts()

fuel
Benzine        17547
Diesel          8727
LPG/CNG          362
Electric         188
LPG/Benzine       19
Name: count, dtype: int64

In [181]:
df.drop('fuel_type', axis=1, inplace=True)

In [182]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29480 entries, 0 to 29479
Data columns (total 46 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28630 non-null  object
 1   short_description        28630 non-null  object
 2   make                     28630 non-null  object
 3   model                    28630 non-null  object
 4   location                 28630 non-null  object
 5   price                    28630 non-null  float64
 6   body_type                28630 non-null  object
 7   type                     28630 non-null  object
 8   doors                    28271 non-null  object
 9   country_version          16889 non-null  object
 10  offer_number             23100 non-null  object
 11  warranty                 15784 non-null  object
 12  mileage                  28629 non-null  object
 13  first_registration       28628 non-null  object
 14  gearbox                  28382 non-null  object
 15  colour                   26906 non-null  object
 16  paint                    14495 non-null  object
 17  desc                     28047 non-null  object
 18  seller                   28630 non-null  object
 19  seats                    25505 non-null  object
 20  power                    28058 non-null  object
 21  engine_size              27227 non-null  object
 22  gears                    18954 non-null  object
 23  co₂emissions             18594 non-null  object
 24  manufacturer_colour      21787 non-null  object
 25  drivetrain               16893 non-null  object
 26  cylinders                18852 non-null  object
 27  fuel_consumption         23385 non-null  object
 28  comfort_convenience      25433 non-null  object
 29  entertainment_media      23644 non-null  object
 30  safety_security          25415 non-null  object
 31  extras                   23480 non-null  object
 32  empty_weight             17758 non-null  object
 33  model_code               8367 non-null   object
 34  general_inspection       12254 non-null  object
 35  full_service_history     12565 non-null  object
 36  nonsmoker_vehicle        11594 non-null  object
 37  emission_class           17859 non-null  object
 38  emissions_sticker        9414 non-null   object
 39  upholstery_colour        14569 non-null  object
 40  upholstery               18610 non-null  object
 41  production_date          5908 non-null   float64
 42  previous_owner           14015 non-null  object
 43  energy_efficiency_class  7804 non-null   object
 44  co₂efficiency            7804 non-null   object
 45  fuel                     26843 non-null  object
dtypes: float64(2), object(44)
memory usage: 10.3+ MB

In [183]:
df

,make_model,short_description,make,model,location,price,body_type,type,doors,country_version,...,nonsmoker_vehicle,emission_class,emissions_sticker,upholstery_colour,upholstery,production_date,previous_owner,energy_efficiency_class,co₂efficiency,fuel
0,Mercedes-Benz A 160,CDi,Mercedes-Benz,A 160,P.I. EL PALMAR C/FORJA 6 11500 PUERTO DE SANT...,16950.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diesel
1,Mercedes-Benz EQE 350,350+,Mercedes-Benz,EQE 350,APARTADO DE CORREOS 1032 26140 LOGROÑO ES,80900.0,Compact,Pre-registered,4,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electric
2,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A 45 AMG,PORT. TARRACO MOLL DE LLEVANT Nº 5 LOC. 6-8 4...,69900.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benzine
3,Mercedes-Benz A 35 AMG,4Matic+ 7G-DCT,Mercedes-Benz,A 35 AMG,Carrer de Provença 31 Local 8029 BARCELONA ES,46990.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benzine
4,Mercedes-Benz A 45 AMG,200CDI BE Line 4M 7G-DCT,Mercedes-Benz,A 45 AMG,CARRIL ARAGONES 4 30007 CASILLAS ES,16800.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diesel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29475,Volvo S40,2.4i Momentum/ Airco/ NAP/ APK/ Elek. Ramen,Volvo,S40,Stobbeweg 6 2461 EX TER AAR NL,5499.0,Sedan,Used,4,NaN,...,NaN,Euro 4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benzine
29476,Volvo C30,1.6 D DRIVe Start/Stop R-design,Volvo,C30,Sur rendez-vous 5060 Sambreville BE,7300.0,Sedan,Used,3,Belgium,...,NaN,Euro 5,NaN,Black,NaN,NaN,"[96,000 km, 04/2011]",NaN,NaN,Diesel
29477,Volvo S90,T5 AUT(8) MOMENTUM BUSINESS SCHUIFDAK 360GR CA...,Volvo,S90,Bergambachterstraat 5 2871 JB SCHOONHOVEN NL,29900.0,Sedan,Used,4,NaN,...,NaN,Euro 6,NaN,Other,Full leather,NaN,NaN,NaN,NaN,Benzine
29478,Volvo S80,2.9 Executive G. NETTE AUTO! LEER! NAVI! CRUIS...,Volvo,S80,Lage Ham 106 5102 AE DONGEN NL,4440.0,Sedan,Used,4,NaN,...,NaN,Euro 3,NaN,Beige,Full leather,NaN,"[230,047 km, 07/2002]",NaN,NaN,Benzine
29479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [184]:
df.warranty.value_counts()

warranty
12 months     9545
Yes           2319
24 months     1515
60 months      968
6 months       398
              ...
55 months        1
99 months        1
122 months       1
44 months        1
4 months         1
Name: count, Length: 65, dtype: int64

In [185]:
df.warranty = df.warranty.str.replace('months', '')

In [186]:
df.warranty[df.warranty == 'Yes']

29       Yes
58       Yes
63       Yes
65       Yes
67       Yes
        ...
29184    Yes
29185    Yes
29208    Yes
29223    Yes
29231    Yes
Name: warranty, Length: 2319, dtype: object

In [187]:
df.warranty.sample(20)

1895     NaN
7592     NaN
8352     NaN
16478    NaN
10228    NaN
373      12
7451     NaN
3350     Yes
1810     NaN
19990    NaN
18785    12
26012    12
11094    12
4748     60
7174     12
2854     60
25676    12
9699      6
22560    NaN
27490    NaN
Name: warranty, dtype: object

In [188]:
df['warranty'] = df['warranty'].replace("Yes", 1)

In [189]:
df['warranty'].value_counts()

warranty
12      9545
1       2319
24      1515
60       968
6        398
        ...
55         1
99         1
122        1
44         1
4          1
Name: count, Length: 65, dtype: int64

In [190]:
df.mileage = df.mileage.str.replace('km', '').str.strip().astype('float')

In [191]:
df['mileage']

0        120200.0
1          5000.0
2         18900.0
3         18995.0
4        197000.0
           ...
29475    145000.0
29476     96000.0
29477     94343.0
29478    230047.0
29479         NaN
Name: mileage, Length: 29480, dtype: float64

In [192]:
df['first_registration']

0        06/2016
1        06/2022
2        07/2020
3        01/2020
4        09/2015
          ...
29475    06/2004
29476    04/2011
29477    11/2017
29478    07/2002
29479        NaN
Name: first_registration, Length: 29480, dtype: object

In [193]:
df['first_registration'] = pd.to_datetime(df['first_registration'], format='%m/%Y', errors='coerce')

In [194]:
df['first_registration']

0       2016-06-01
1       2022-06-01
2       2020-07-01
3       2020-01-01
4       2015-09-01
           ...
29475   2004-06-01
29476   2011-04-01
29477   2017-11-01
29478   2002-07-01
29479          NaT
Name: first_registration, Length: 29480, dtype: datetime64[ns]

In [195]:
current_year = 2022
df['car_age'] = current_year - df['first_registration'].dt.year

In [196]:
df.drop('first_registration', axis=1, inplace=True)

In [197]:
df.head()

,make_model,short_description,make,model,location,price,body_type,type,doors,country_version,...,emission_class,emissions_sticker,upholstery_colour,upholstery,production_date,previous_owner,energy_efficiency_class,co₂efficiency,fuel,car_age
0,Mercedes-Benz A 160,CDi,Mercedes-Benz,A 160,P.I. EL PALMAR C/FORJA 6 11500 PUERTO DE SANT...,16950.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diesel,6.0
1,Mercedes-Benz EQE 350,350+,Mercedes-Benz,EQE 350,APARTADO DE CORREOS 1032 26140 LOGROÑO ES,80900.0,Compact,Pre-registered,4,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Electric,0.0
2,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A 45 AMG,PORT. TARRACO MOLL DE LLEVANT Nº 5 LOC. 6-8 4...,69900.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benzine,2.0
3,Mercedes-Benz A 35 AMG,4Matic+ 7G-DCT,Mercedes-Benz,A 35 AMG,Carrer de Provença 31 Local 8029 BARCELONA ES,46990.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Benzine,2.0
4,Mercedes-Benz A 45 AMG,200CDI BE Line 4M 7G-DCT,Mercedes-Benz,A 45 AMG,CARRIL ARAGONES 4 30007 CASILLAS ES,16800.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Diesel,7.0

In [198]:
df['power_kw'] = df['power'].str.extract(r'(\d+)\s*kW').astype(float)

In [199]:
df['power_kw'].info

<bound method Series.info of 0          NaN
1        215.0
2        310.0
3        225.0
4        100.0
         ...
29475    125.0
29476     84.0
29477    187.0
29478    147.0
29479      NaN
Name: power_kw, Length: 29480, dtype: float64>

In [200]:
df['power_hp'] = df['power'].str.extract(r'\((\d+)\s*hp\)').astype(float)

In [201]:
df['power_hp']

0          NaN
1        292.0
2        421.0
3        306.0
4        136.0
         ...
29475    170.0
29476    114.0
29477    254.0
29478    200.0
29479      NaN
Name: power_hp, Length: 29480, dtype: float64

In [202]:
df.drop('power', axis=1, inplace=True)

In [203]:
df.head()

,make_model,short_description,make,model,location,price,body_type,type,doors,country_version,...,upholstery_colour,upholstery,production_date,previous_owner,energy_efficiency_class,co₂efficiency,fuel,car_age,power_kw,power_hp
0,Mercedes-Benz A 160,CDi,Mercedes-Benz,A 160,P.I. EL PALMAR C/FORJA 6 11500 PUERTO DE SANT...,16950.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,Diesel,6.0,NaN,NaN
1,Mercedes-Benz EQE 350,350+,Mercedes-Benz,EQE 350,APARTADO DE CORREOS 1032 26140 LOGROÑO ES,80900.0,Compact,Pre-registered,4,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,Electric,0.0,215.0,292.0
2,Mercedes-Benz A 45 AMG,S 4Matic+ 8G-DCT,Mercedes-Benz,A 45 AMG,PORT. TARRACO MOLL DE LLEVANT Nº 5 LOC. 6-8 4...,69900.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,Benzine,2.0,310.0,421.0
3,Mercedes-Benz A 35 AMG,4Matic+ 7G-DCT,Mercedes-Benz,A 35 AMG,Carrer de Provença 31 Local 8029 BARCELONA ES,46990.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,Benzine,2.0,225.0,306.0
4,Mercedes-Benz A 45 AMG,200CDI BE Line 4M 7G-DCT,Mercedes-Benz,A 45 AMG,CARRIL ARAGONES 4 30007 CASILLAS ES,16800.0,Compact,Used,5,Spain,...,NaN,NaN,NaN,NaN,NaN,NaN,Diesel,7.0,100.0,136.0

In [204]:
df['engine_size']

0            NaN
1           1 cc
2        1991 cc
3        1991 cc
4        2143 cc
          ...
29475    2435 cc
29476    1560 cc
29477    1969 cc
29478    2922 cc
29479        NaN
Name: engine_size, Length: 29480, dtype: object

In [205]:
df.engine_size = df.engine_size.str.replace('cc', '').str.strip().astype('float')

In [206]:
df['engine_size']

0           NaN
1           1.0
2        1991.0
3        1991.0
4        2143.0
          ...
29475    2435.0
29476    1560.0
29477    1969.0
29478    2922.0
29479       NaN
Name: engine_size, Length: 29480, dtype: float64

In [207]:
df['empty_weight']

0            NaN
1            NaN
2            NaN
3            NaN
4        1545 kg
          ...
29475    1357 kg
29476    1356 kg
29477    1617 kg
29478    1573 kg
29479        NaN
Name: empty_weight, Length: 29480, dtype: object

In [208]:
df.empty_weight = df.empty_weight.str.replace('kg', '').str.strip().astype('float')

In [209]:
df['empty_weight']

0           NaN
1           NaN
2           NaN
3           NaN
4        1545.0
          ...
29475    1357.0
29476    1356.0
29477    1617.0
29478    1573.0
29479       NaN
Name: empty_weight, Length: 29480, dtype: float64

In [210]:
df['emission_class'].value_counts(dropna=False)

emission_class
NaN             11621
Euro 6           6418
Euro 6d-TEMP     3399
Euro 6d          2858
Euro 5           2389
Euro 4           1743
Euro 3            523
Euro 2            217
Euro 1            172
Euro 6c           140
Name: count, dtype: int64

In [211]:
df['emissions_sticker'].value_counts(dropna=False)

emissions_sticker
NaN               20066
4 (Green)          9230
1 (No sticker)      176
3 (Yellow)            6
2 (Red)               2
Name: count, dtype: int64

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29480 entries, 0 to 29479
Data columns (total 47 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   make_model               28630 non-null  object
 1   short_description        28630 non-null  object
 2   make                     28630 non-null  object
 3   model                    28630 non-null  object
 4   location                 28630 non-null  object
 5   price                    28630 non-null  float64
 6   body_type                28630 non-null  object
 7   type                     28630 non-null  object
 8   doors                    28271 non-null  object
 9   country_version          16889 non-null  object
 10  offer_number             23100 non-null  object
 11  warranty                 15784 non-null  object
 12  mileage                  28629 non-null  float64
 13  gearbox                  28382 non-null  object
 14  colour                   26906 non-null  object
 15  paint                    14495 non-null  object
 16  desc                     28047 non-null  object
 17  seller                   28630 non-null  object
 18  seats                    25505 non-null  object
 19  engine_size              27227 non-null  float64
 20  gears                    18954 non-null  object
 21  co₂emissions             18594 non-null  object
 22  manufacturer_colour      21787 non-null  object
 23  drivetrain               16893 non-null  object
 24  cylinders                18852 non-null  object
 25  fuel_consumption         23385 non-null  object
 26  comfort_convenience      25433 non-null  object
 27  entertainment_media      23644 non-null  object
 28  safety_security          25415 non-null  object
 29  extras                   23480 non-null  object
 30  empty_weight             17758 non-null  float64
 31  model_code               8367 non-null   object
 32  general_inspection       12254 non-null  object
 33  full_service_history     12565 non-null  object
 34  nonsmoker_vehicle        11594 non-null  object
 35  emission_class           17859 non-null  object
 36  emissions_sticker        9414 non-null   object
 37  upholstery_colour        14569 non-null  object
 38  upholstery               18610 non-null  object
 39  production_date          5908 non-null   float64
 40  previous_owner           14015 non-null  object
 41  energy_efficiency_class  7804 non-null   object
 42  co₂efficiency            7804 non-null   object
 43  fuel                     26843 non-null  object
 44  car_age                  28628 non-null  float64
 45  power_kw                 28058 non-null  float64
 46  power_hp                 28058 non-null  float64
dtypes: float64(8), object(39)
memory usage: 10.6+ MB

In [241]:
df.columns = df.columns.str.replace('₂', '2')
print(df.co2emissions.value_counts(dropna=False))

co2emissions
NaN                  10886
0 g/km (comb.)        1038
119 g/km (comb.)       393
124 g/km (comb.)       340
129 g/km (comb.)       319
                     ...
7 g/km (comb.)           1
80 g/km (comb.)          1
196  g/km (comb.)        1
100  g/km (comb.)        1
53 g/km (comb.)          1
Name: count, Length: 348, dtype: int64

In [243]:
df['co2emissions'] = df['co2emissions'].str.extract(r'(\d+)').astype(float)

In [247]:
df.model_code.value_counts(dropna=False)

model_code
NaN         21113
8212/AFJ       75
1727/AAM       64
1349/AGI       61
1889/ABU       55
            ...
7593/ANL        1
1727/ABC        1
4136/AEC        1
4136/668        1
9101/449        1
Name: count, Length: 2187, dtype: int64

In [249]:
df.drop('model_code', axis=1, inplace=True)

In [251]:
df.fuel_consumption.value_counts(dropna=False)

fuel_consumption
NaN                         6095
[5 l/100 km (comb.)]         818
[4.9 l/100 km (comb.)]       809
[4.5 l/100 km (comb.)]       690
[5.1 l/100 km (comb.)]       639
                            ...
[6.5 kg/100 km (comb.)]        1
[4 kg/100 km (comb.)]          1
[7 l/100 km (city)]            1
[4.9 l/100 km (country)]       1
[9 l/100 km (country)]         1
Name: count, Length: 219, dtype: int64

In [280]:
df['fuel_consumption'] = df['fuel_consumption'].map(lambda item: item[0] if isinstance(item, list) else item)

In [281]:
df['fuel_consumption_cleaned'] = df['fuel_consumption'].str.extract(r'^([\d\.]+)').astype(float)

In [282]:
df.fuel_consumption_cleaned.value_counts(dropna=False)

fuel_consumption_cleaned
NaN     6095
5.0      831
4.9      812
4.5      690
0.0      652
        ...
16.0       1
57.0       1
61.0       1
14.5       1
44.0       1
Name: count, Length: 162, dtype: int64

In [287]:
df.drop('fuel_consumption', axis=1, inplace=True)

In [290]:
df.previous_owner.value_counts()

previous_owner
[50 km, 06/2022]         64
[10 km, 08/2022]         60
[10 km, 07/2022]         45
[10 km, 05/2022]         44
[10 km, 09/2022]         38
                         ..
[141,808 km, 03/2000]     1
[93,000 km, 09/2010]      1
[24,000 km, 11/2012]      1
[96,200 km, 08/2012]      1
[230,047 km, 07/2002]     1
Name: count, Length: 11664, dtype: int64

In [306]:
df['previous_owner_km'] = df['previous_owner'].map(
    lambda item: item[0] if isinstance(item, list) else item
)

In [310]:
df['previous_owner_km'] = df['previous_owner_km'].str.replace('km', '').str.strip()

In [308]:
df['previous_owner_date'] = df['previous_owner'].map(
    lambda item: item[1] if isinstance(item, list) else item
)

In [ ]:
df['previous_owner_date'] = df['previous_owner_date'].str.extract(r'(\d{4})').astype(float)

In [317]:
df['previous_owner_km'] = df['previous_owner_km'].str.replace(',', '').astype(float)

In [316]:
df['previous_owner_date'].value_counts()

previous_owner_date
2019.0    2039
2022.0    1930
2021.0    1830
2018.0    1496
2020.0    1467
          ...
1956.0       1
1960.0       1
1952.0       1
1930.0       1
1928.0       1
Name: count, Length: 72, dtype: int64

In [318]:
df['previous_owner_km'].value_counts()

previous_owner_km
10.0        322
50.0        118
20.0         79
5000.0       78
100.0        75
           ...
147215.0      1
105733.0      1
64863.0       1
156517.0      1
230047.0      1
Name: count, Length: 7794, dtype: int64

In [320]:
df.drop('previous_owner_cleaned', axis=1, inplace=True)

In [322]:
df.power_hp.value_counts(dropna=False)

power_hp
150.0     1992
NaN       1422
131.0     1356
120.0     1182
110.0     1166
          ...
1014.0       1
775.0        1
640.0        1
243.0        1
35.0         1
Name: count, Length: 352, dtype: int64

In [325]:
df.power_kw.value_counts()

power_kw
110.0    1992
96.0     1356
88.0     1182
81.0     1166
66.0     1110
         ...
746.0       1
570.0       1
471.0       1
179.0       1
26.0        1
Name: count, Length: 351, dtype: int64

In [326]:
df.drop('power_kw', axis=1, inplace=True)

In [330]:
columns_to_drop1 = ['short_description', 'location', 'offer_number', 'manufacturer_colour', 'desc']

In [331]:
df = df.drop(columns=columns_to_drop1)

In [334]:
df = df.drop(columns=['make_model'])

In [365]:
df = df.drop(columns=['previous_owner'])

In [340]:
df['type'] = df['type'].str.lower().str.strip()
df['body_type'] = df['body_type'].str.lower().str.strip()
df['fuel'] = df['fuel'].str.lower().str.strip()
df['gearbox'] = df['gearbox'].str.lower().str.strip()
df['emission_class'] = df['emission_class'].str.lower().str.strip()
df['drivetrain'] = df['drivetrain'].str.lower().str.strip()
df['seller'] = df['seller'].str.lower().str.strip()

In [351]:
df = df[(df['price'] > 100) & (df['price'] < 1_000_000)]

In [353]:
df = df[df['mileage'] >= 0]
df = df[df['engine_size'] >= 0]

In [366]:
df.isna().sum()

make                            0
model                           0
price                           0
body_type                       0
type                            0
doors                         149
country_version             11057
warranty                    12173
mileage                         0
gearbox                       159
colour                       1502
paint                       13224
seller                          0
seats                        2582
engine_size                     0
gears                        8729
co2emissions                 8899
drivetrain                  10804
cylinders                    8560
comfort_convenience          2716
entertainment_media          4364
safety_security              2732
extras                       4470
empty_weight                 9821
general_inspection          15366
full_service_history        15035
nonsmoker_vehicle           16021
emission_class               9622
emissions_sticker           18104
upholstery_colour           13290
upholstery                   9302
production_date             21521
energy_efficiency_class     19659
co2efficiency               19659
fuel                         1407
car_age                         2
power_hp                      384
fuel_consumption_cleaned     3932
previous_owner_km           13637
previous_owner_date         13637
dtype: int64

In [370]:
df['general_inspection'] = df['general_inspection'].apply(
    lambda x: '2022' if str(x).strip().lower() == 'new' else str(x)[-4:] if pd.notna(x) and '/' in str(x) else np.nan)

In [373]:
df['general_inspection'].astype(float)

1           NaN
2           NaN
3           NaN
4           NaN
5        2022.0
          ...
29474       NaN
29475    2023.0
29476       NaN
29477    2022.0
29478    2023.0
Name: general_inspection, Length: 27226, dtype: float64

In [380]:
df['emissions_sticker'] = df['emissions_sticker'].str.extract(r'(\d+)').astype(float)

In [382]:
df.emissions_sticker.value_counts(dropna=False)

emissions_sticker
NaN    18104
4.0     8952
1.0      162
3.0        6
2.0        2
Name: count, dtype: int64

In [383]:
df.T

,1,2,3,4,5,7,8,9,10,11,...,29468,29469,29470,29471,29472,29474,29475,29476,29477,29478
make,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,Mercedes-Benz,...,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo,Volvo
model,EQE 350,A 45 AMG,A 35 AMG,A 45 AMG,C 160,A 220,A 35 AMG,A 200,A 160,A 45 AMG,...,S90,S90,S90,V40,S60,S90,S40,C30,S90,S80
price,80900.0,69900.0,46990.0,16800.0,4690.0,26900.0,44999.0,23900.0,14200.0,37999.0,...,38000.0,27190.0,27190.0,13000.0,4999.0,37600.0,5499.0,7300.0,29900.0,4440.0
body_type,compact,compact,compact,compact,compact,compact,compact,compact,compact,compact,...,sedan,sedan,sedan,sedan,sedan,sedan,sedan,sedan,sedan,sedan
type,pre-registered,used,used,used,used,used,used,used,used,used,...,used,used,used,used,used,used,used,used,used,used
doors,4,5,5,5,3,5,5,5,5,5,...,4,4,4,5,4,4,4,3,4,4
country_version,Spain,Spain,Spain,Spain,Germany,Spain,NaN,Spain,NaN,Spain,...,NaN,Spain,Spain,NaN,Spain,Spain,NaN,Belgium,NaN,NaN
warranty,24,12,12,12,NaN,24,NaN,12,12,12,...,NaN,12,12,NaN,12,12,NaN,13,12,NaN
mileage,5000.0,18900.0,18995.0,197000.0,165000.0,48900.0,56876.0,21854.0,99016.0,90000.0,...,44873.0,93757.0,93757.0,114000.0,166512.0,40345.0,145000.0,96000.0,94343.0,230047.0
gearbox,automatic,automatic,automatic,automatic,manual,automatic,automatic,automatic,manual,automatic,...,automatic,automatic,automatic,manual,manual,automatic,automatic,manual,automatic,automatic
colour,NaN,Grey,Yellow,White,Black,Grey,Grey,White,Grey,Black,...,Black,Black,Black,Grey,Black,Black,Grey,Grey,Blue,Grey
paint,NaN,NaN,NaN,Metallic,Metallic,Metallic,NaN,NaN,Metallic,Metallic,...,Metallic,NaN,NaN,Metallic,NaN,NaN,NaN,Metallic,Metallic,NaN
seller,dealer,dealer,dealer,dealer,dealer,dealer,dealer,dealer,dealer,dealer,...,private seller,dealer,dealer,private seller,dealer,dealer,dealer,dealer,dealer,dealer
seats,5,5,5,5,4,5,NaN,5,5,5,...,5,5,5,5,5,4,5,4,5,5
engine_size,1.0,1991.0,1991.0,2143.0,1799.0,1991.0,1991.0,1991.0,1461.0,1991.0,...,1969.0,1969.0,1969.0,1969.0,2521.0,1969.0,2435.0,1560.0,1969.0,2922.0
gears,9,8,7,7,6,7,NaN,1,5,7,...,8,8,8,6,5,8,5,6,8,NaN
co2emissions,0.0,NaN,NaN,NaN,196.0,NaN,168.0,NaN,98.0,NaN,...,NaN,NaN,NaN,94.0,NaN,NaN,217.0,99.0,149.0,251.0
drivetrain,NaN,4wd,4wd,4wd,rear,front,NaN,front,front,4wd,...,NaN,front,front,front,front,4wd,front,front,NaN,front
cylinders,NaN,4,4,4,4,4,NaN,4,4,4,...,4,4,4,4,5,4,5,4,4,6
comfort_convenience,NaN,NaN,Air conditioning Automatic climate control Pow...,Air conditioning Electrical side mirrors Multi...,Air conditioning Armrest Automatic climate con...,Air conditioning Automatic climate control Pow...,Multi-function steering wheel Navigation syste...,Air conditioning Automatic climate control Ele...,Air conditioning Armrest Electrical side mirro...,Air conditioning Electrical side mirrors Power...,...,360° camera Air conditioning Armrest Automatic...,Air conditioning Automatic climate control Mul...,Air conditioning Automatic climate control Mul...,Air conditioning Armrest Automatic climate con...,Air conditioning Automatic climate control Ele...,Air conditioning Automatic climate control Mul...,Air conditioning Armrest Automatic climate con...,Air conditioning Armrest Automatic climate con...,Air conditioning Armrest Automatic climate con...,Air conditioning Armrest Cruise control Electr...
entertainment_media,NaN,NaN,USB,Bluetooth CD player MP3 USB,CD player On-board computer Radio,USB,NaN,NaN,Bluetooth CD player MP3 On-board computer Radio,NaN,...,Android Auto Apple CarPlay Bluetooth CD player...,Hands-free equipment USB,Hands-free equipment USB,Bluetooth Hands-free equipment On-board comput...,On-board computer,Bluetooth USB,On-board computer Radio,Bluetooth CD player Hands-free equipment MP3 O...,Android Auto Apple CarPlay Bluetooth Hands-fre...,On-board computer
safety_security,NaN,NaN,ABS Central door lock Driver-side airbag Elect...,ABS Central door lock Driver-side airbag Elect...,ABS Bi-Xenon headlights Central door lock Driv...,ABS Central door lock Driver-side airbag Elect...,Emergency brake assistant,ABS Central door lock Driver-side airbag Elect...,ABS Alarm system Central door lock Central doo...,ABS Central door lock Driver-side airbag Isofix,...,ABS Adaptive Cruise Control Adaptive headlight...,ABS Central door lock Driver-side airbag Elect...,ABS Central door lock Driver-side airbag Elect...,ABS Alarm system Central door lock with remote...,ABS Central door lock Driver-side airbag Elect...,ABS Central door lock Driver-side airbag Elect...,ABS Central door lock Central door lock with r...,ABS Alarm system Central door lock with remote...,Adaptive Cruise Control Adaptive headlights Da...,ABS Alarm system Central door lock Central doo...
extras,NaN,NaN,Sport seats,NaN,"Alloy wheels (17"") Catalytic Converter Emergen...",NaN,Sport package,Alloy wheels,Alloy wheels Spoiler,Alloy wheels Sport seats,...,"Alloy wheels (21"") Ambient lighting Automatica...",Alloy wheels,Alloy wheels,All season tyres Ambient lighting Cargo barrie...,Alloy wheels,Alloy wheels,"Alloy wheels (16"") Trailer hitch",Alloy wheels Automatically dimming interior mi...,"Alloy wheels (18"") Automatically dimming inter...",Alloy wheels Automatically dimming interior mi...
empty_weight,NaN,NaN,NaN,1545.0,1465.0,1450.0,NaN,1365.0,1295.0,1555.0,...,1930.0,1683.0,1683.0,1532.0,1550.0,2077.0,1357.0,1356.0,1617.0,1573.0
general_inspection,NaN,NaN,NaN,NaN,2022,NaN,NaN,NaN,NaN,NaN,...,2024,NaN,NaN,2023,NaN,NaN,2023,NaN,2022,2023
full_service_history,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,...,Yes,NaN,NaN,Yes,NaN,NaN,Yes,Yes,Yes,NaN
nonsmoker_vehicle,NaN,NaN,NaN,NaN,Yes,NaN,NaN,NaN,NaN,NaN,...,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emission_class,NaN,NaN,NaN,NaN,euro 4,NaN,euro 6,NaN,euro 6,NaN,...,euro 6d-temp,NaN,NaN,euro 6,NaN,NaN,euro 4,euro 5,euro 6,euro 3
emissions_sticker,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
upholstery_colour,NaN,NaN,NaN,NaN,Black,NaN,Black,NaN,Black,NaN,...,Black,NaN,NaN,Black,NaN,NaN,NaN,Black,Other,Beige
upholstery,NaN,NaN,NaN,NaN,Cloth,NaN,Full leather,NaN,Cloth,NaN,...,Full leather,NaN,NaN,Cloth,NaN,NaN,NaN,NaN,Full leather,Full leather
production_date,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
energy_efficiency_class,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
co2efficiency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fuel,electric,benzine,benzine,diesel,benzine,benzine,benzine,diesel,diesel,benzine,...,benzine,diesel,diesel,diesel,benzine,NaN,benzine,diesel,benzine,benzine
car_age,0.0,2.0,2.0,7.0,17.0,3.0,3.0,4.0,7.0,6.0,...,4.0,4.0,4.0,4.0,18.0,3.0,18.0,11.0,5.0,20.0
power_hp,292.0,421.0,306.0,136.0,122.0,190.0,306.0,139.0,90.0,381.0,...,310.0,190.0,190.0,120.0,209.0,392.0,170.0,114.0,254.0,200.0
fuel_consumption_cleaned,NaN,8.4,7.3,4.9,8.2,6.1,0.0,5.4,3.8,6.9,...,7.6,4.4,4.4,3.6,9.1,2.0,9.1,3.8,6.5,10.4
previous_owner_km,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,44873.0,NaN,NaN,114000.0,NaN,NaN,NaN,96000.0,NaN,230047.0
previous_owner_date,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2018.0,NaN,NaN,2018.0,NaN,NaN,NaN,2011.0,NaN,2002.0

In [384]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 27226 entries, 1 to 29478
Data columns (total 40 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   make                      27226 non-null  object
 1   model                     27226 non-null  object
 2   price                     27226 non-null  float64
 3   body_type                 27226 non-null  object
 4   type                      27226 non-null  object
 5   doors                     27077 non-null  object
 6   country_version           16169 non-null  object
 7   warranty                  15053 non-null  object
 8   mileage                   27226 non-null  float64
 9   gearbox                   27067 non-null  object
 10  colour                    25724 non-null  object
 11  paint                     14002 non-null  object
 12  seller                    27226 non-null  object
 13  seats                     24644 non-null  object
 14  engine_size               27226 non-null  float64
 15  gears                     18497 non-null  object
 16  co2emissions              18327 non-null  float64
 17  drivetrain                16422 non-null  object
 18  cylinders                 18666 non-null  object
 19  comfort_convenience       24510 non-null  object
 20  entertainment_media       22862 non-null  object
 21  safety_security           24494 non-null  object
 22  extras                    22756 non-null  object
 23  empty_weight              17405 non-null  float64
 24  general_inspection        11860 non-null  object
 25  full_service_history      12191 non-null  object
 26  nonsmoker_vehicle         11205 non-null  object
 27  emission_class            17604 non-null  object
 28  emissions_sticker         9122 non-null   float64
 29  upholstery_colour         13936 non-null  object
 30  upholstery                17924 non-null  object
 31  production_date           5705 non-null   float64
 32  energy_efficiency_class   7567 non-null   object
 33  co2efficiency             7567 non-null   object
 34  fuel                      25819 non-null  object
 35  car_age                   27224 non-null  float64
 36  power_hp                  26842 non-null  float64
 37  fuel_consumption_cleaned  23294 non-null  float64
 38  previous_owner_km         13589 non-null  float64
 39  previous_owner_date       13589 non-null  float64
dtypes: float64(12), object(28)
memory usage: 9.5+ MB

In [385]:
df.to_csv('cleaned_data.csv', index=False)